apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
    - image: tons/whoami-mn
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubeContext: default
  helm:
    releases:
      - name: whoami-mn
        namespace: whoami-mn
        chartPath: ./src/main/helm
        artifactOverrides:
          image.name: tons/whoami-mn
