{{- if .Values.ingress.enabled -}}
{{- $fullName := include "whoami-mn.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "whoami-mn.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    certmanager.k8s.io/issuer: {{ .Values.ingress.certIssuer | quote }}
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
