name: Java CI with Gradle, Docker and Kubernetes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run tests
      run: ./gradlew test

    - name: Authenticate with Docker registry
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with Jib
      run: ./gradlew jib --image tons/whoami-mn:ci

    - name: Lint Helm Chart
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm lint src/main/helm/

    - name: Deploy to Kubernetes
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm --kube-context nuc upgrade --install --set image.name=tons/whoami-mn:ci --set image.pullPolicy=Always --namespace whoami-mn-dev whoami-mn src/main/helm/
        kubeconfig: '${{ secrets.KUBE_CONFIG }}'
